2024-08-12 11:02:13,681 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:02:14,705 - INFO - 任务已终止
2024-08-12 11:02:15,133 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:02:15,220 - INFO - 数据拉取成功
2024-08-12 11:02:18,713 - INFO - 任务已终止
2024-08-12 11:02:22,761 - INFO - 任务已终止
2024-08-12 11:02:26,769 - INFO - 任务已终止
2024-08-12 11:02:30,772 - INFO - 任务已终止
2024-08-12 11:02:34,781 - INFO - 任务已终止
2024-08-12 11:02:38,783 - INFO - 任务已终止
2024-08-12 11:02:42,789 - INFO - 任务已终止
2024-08-12 11:02:46,401 - INFO - 任务已终止
2024-08-12 11:05:02,500 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:05:03,182 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:05:03,227 - INFO - 数据拉取成功
2024-08-12 11:05:03,551 - INFO - 任务已终止
2024-08-12 11:05:10,561 - INFO - 任务已终止
2024-08-12 11:07:21,358 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:07:22,276 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:07:22,311 - INFO - 数据拉取成功
2024-08-12 11:07:22,383 - INFO - 任务已终止
2024-08-12 11:07:26,388 - INFO - 任务已终止
2024-08-12 11:07:30,408 - INFO - 任务已终止
2024-08-12 11:07:34,417 - INFO - 任务已终止
2024-08-12 11:07:38,427 - INFO - 任务已终止
2024-08-12 11:07:42,433 - INFO - 任务已终止
2024-08-12 11:07:46,440 - INFO - 任务已终止
2024-08-12 11:07:50,449 - INFO - 任务已终止
2024-08-12 11:07:54,454 - INFO - 任务已终止
2024-08-12 11:07:55,919 - INFO - 任务已终止
2024-08-12 11:08:49,018 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:08:49,460 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:08:49,497 - INFO - 数据拉取成功
2024-08-12 11:08:50,032 - INFO - 任务已终止
2024-08-12 11:08:57,039 - INFO - 任务已终止
2024-08-12 11:09:23,335 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:09:24,350 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:09:24,358 - INFO - 任务已终止
2024-08-12 11:09:24,388 - INFO - 数据拉取成功
2024-08-12 11:09:28,366 - INFO - 任务已终止
2024-08-12 11:09:32,422 - INFO - 任务已终止
2024-08-12 11:09:36,426 - INFO - 任务已终止
2024-08-12 11:09:40,434 - INFO - 任务已终止
2024-08-12 11:09:44,442 - INFO - 任务已终止
2024-08-12 11:09:47,282 - INFO - 任务已终止
2024-08-12 11:11:22,134 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:11:23,132 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:11:23,162 - INFO - 任务已终止
2024-08-12 11:11:23,176 - INFO - 数据拉取成功
2024-08-12 11:11:27,167 - INFO - 任务已终止
2024-08-12 11:11:31,181 - INFO - 任务已终止
2024-08-12 11:11:35,187 - INFO - 任务已终止
2024-08-12 11:11:39,192 - INFO - 任务已终止
2024-08-12 11:11:43,200 - INFO - 任务已终止
2024-08-12 11:11:47,209 - INFO - 任务已终止
2024-08-12 11:11:51,216 - INFO - 任务已终止
2024-08-12 11:11:55,219 - INFO - 任务已终止
2024-08-12 11:11:59,221 - INFO - 任务已终止
2024-08-12 11:12:03,229 - INFO - 任务已终止
2024-08-12 11:12:07,234 - INFO - 任务已终止
2024-08-12 11:12:11,238 - INFO - 任务已终止
2024-08-12 11:12:15,248 - INFO - 任务已终止
2024-08-12 11:12:19,250 - INFO - 任务已终止
2024-08-12 11:12:23,256 - INFO - 任务已终止
2024-08-12 11:19:52,487 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:19:53,382 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-12 11:19:53,418 - INFO - 数据拉取成功
2024-08-12 11:19:53,508 - INFO - 任务已终止
2024-08-12 11:19:57,514 - INFO - 任务已终止
2024-08-12 11:20:01,540 - INFO - 任务已终止
2024-08-12 11:20:05,547 - INFO - 任务已终止
2024-08-12 11:20:09,555 - INFO - 任务已终止
2024-08-12 11:20:13,561 - INFO - 任务已终止
2024-08-12 11:20:17,568 - INFO - 任务已终止
2024-08-12 11:20:21,573 - INFO - 任务已终止
2024-08-12 11:20:25,581 - INFO - 任务已终止
2024-08-12 11:20:29,586 - INFO - 任务已终止
2024-08-12 11:20:33,593 - INFO - 任务已终止
2024-08-12 11:20:37,601 - INFO - 任务已终止
2024-08-12 11:20:41,606 - INFO - 任务已终止
2024-08-12 11:20:45,609 - INFO - 任务已终止
2024-08-12 11:20:49,618 - INFO - 任务已终止
2024-08-12 11:20:53,630 - INFO - 任务已终止
2024-08-12 11:20:57,634 - INFO - 任务已终止
2024-08-12 11:21:01,642 - INFO - 任务已终止
2024-08-12 11:21:05,650 - INFO - 任务已终止
2024-08-13 11:48:29,434 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 11:48:30,005 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 11:48:30,076 - INFO - 数据拉取成功
2024-08-13 11:48:30,465 - INFO - 任务已终止
2024-08-13 11:48:34,468 - INFO - 任务已终止
2024-08-13 11:48:38,474 - INFO - 任务已终止
2024-08-13 11:48:42,480 - INFO - 任务已终止
2024-08-13 11:48:46,483 - INFO - 任务已终止
2024-08-13 20:37:29,054 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 20:37:29,476 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 20:37:29,516 - INFO - 数据拉取成功
2024-08-13 20:37:30,070 - INFO - 任务已终止
2024-08-13 20:37:34,076 - INFO - 任务已终止
2024-08-13 20:42:36,989 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 20:42:37,433 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 20:42:37,479 - INFO - 数据拉取成功
2024-08-13 20:42:38,005 - INFO - 任务已终止
2024-08-13 20:42:42,012 - INFO - 任务已终止
2024-08-13 20:42:51,054 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))
2024-08-13 20:42:53,061 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1054368f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:42:55,072 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105437070>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:42:57,078 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105437820>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:42:59,086 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105436f20>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:01,089 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105436bf0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:03,093 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10546cbb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:05,134 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10546d4b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:07,145 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10546c130>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:09,153 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10546c4f0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:11,161 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105437b50>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:13,172 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105437250>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:15,175 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1054364d0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:17,182 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105436cb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:19,192 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1054375b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:21,202 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105437df0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:23,205 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10546cc70>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:25,215 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105437f70>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:27,221 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10546d2a0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:29,232 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105434760>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:31,237 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105436cb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:33,242 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1054375b0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:35,253 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105436980>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:43:37,259 - ERROR - 调用获取引擎任务接口 发生错误 错误信息为：HTTPConnectionPool(host='localhost', port=8089): Max retries exceeded with url: /openapi/engine/task/fetch (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x105437bb0>: Failed to establish a new connection: [Errno 61] Connection refused'))
2024-08-13 20:44:06,210 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 20:44:06,677 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 20:44:06,717 - INFO - 数据拉取成功
2024-08-13 20:44:07,226 - INFO - 任务已终止
2024-08-13 20:44:11,236 - INFO - 任务已终止
2024-08-13 20:47:11,214 - INFO - 引擎获取任务成功 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 20:47:11,684 - INFO - 开始执行任务 任务id: 99c1dfe9-5da7-4e50-b2eb-9566b81c75a4
2024-08-13 20:47:11,731 - INFO - 数据拉取成功
2024-08-13 20:47:12,229 - INFO - 任务已终止
2024-08-13 20:47:16,238 - INFO - 任务已终止
2024-08-13 20:47:23,266 - INFO - 任务已终止
